# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25c0a8b76940e0e90a2d298f122513e5877a5d430de08e952a071601a69f88c682798090d733afffcc0160e328242e7fdf187c554685b4b1cbbaff6e8f0985b9

test:
  secret_key_base: a65533ef0a48dfe84daaec7a1ec6d845fc4bfab2629ed2a973d96a9c0fbc3e904d5b0f9ef2af5e3ca7b5fc5ee117c8fd917a702613d06db44b6ada8d6909d524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
